//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resort_Forest_Park.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string id_login { get; set; }
        public int id_staff { get; set; }
        public System.DateTime time { get; set; }
        public int id_typeLogin { get; set; }
    
        public virtual TypeLogin TypeLogin { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
